config/routes.rb
Rails.application.routes.draw do
  resources :list_items
  resources :lists
  devise_for :users
  root to: 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :user_id, presence: true
  has_many :list_items
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :list

  validates :list, presence: true
  validates :title, presence: true
  enum state: [ :not_started, :in_progress, :completed]

  def state
    ListItem.states.key(read_attribute(:state)).humanize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :authenticate_user!

  def create
    @list = List.find(params[:list_id])
    if !@list
      render json: 'No such list', status: :unprocessable_entity
    end
    @list_item = ListItem.new(list_item_params)
    @list_item.list = @list
    if @list_item.save
      render json: @list_item
    else
      render json: @list_item, status: :unprocessable_entity
    end
  end

  def update
    @list_item = ListItem.find(params[:id])
    if @list_item.update(list_item_params)
      render json: @list_item
    else
      render json: @list_item, status: :unprocessable_entity
    end
  end

  def destroy
    @list_item = ListItem.find_by(id: params[:id])
    if @list_item
      @list_item.destroy
      head :no_content
    else
      head :bad_request
    end
  end

  private

  def list_item_params
    params.require(:list_item).permit(:title, :description, :state, :id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = current_user.lists.includes(:list_items)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to '/', flash: {success: 'List created successfully'}
    else
      flash.now[:error] = @list.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def destroy
    @list = List.find_by(id: params[:id], user_id: current_user.id)
    if @list
      @list.destroy
      head :no_content
    else
      head :bad_request
    end
  end

  private

  def list_params
    params.require(:list).permit(:title, :description, :list_items)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      msg = concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissable fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Harshith's Todo App!
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a{href: "/", class: 'navbar-brand'} Todo Lists!
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li
              = link_to 'Sign Out', destroy_user_session_path, method: :delete
          - else
            %li
              = link_to 'Sign In', new_user_session_path
    .container
      - flash_messages
      = yield

app/views/lists/_form.html.haml
= form_for @list, url: {action: 'create'}, html: {class: 'form-horizontal'} do |f|
  .form-group
    = f.label 'Title', class: 'col-xs-3 control-label'
    .col-xs-9
      = f.text_field :title, placeholder: 'Title', class: 'form-control', value: @list.title
  .form-group
    = f.label 'Description', class: 'col-xs-3 control-label'
    .col-xs-9
      = f.text_field :description, placeholder: 'Description', class: 'form-control', value: @list.description
  .form-group
    .col-xs-9.col-xs-offset-3
      = f.submit 'Create', class:'btn btn-primary'

app/views/lists/index.html.haml
%h3.title
  My ToDo Lists
  = link_to 'New List', new_list_path, class: 'btn btn-primary'
= react_component 'Lists', { data: @lists.as_json(include: :list_items) }#, { prerender: true }

app/views/lists/new.html.haml
%h3.col-xs-offset-3 Create new todo list
.well.col-xs-6.col-xs-offset-3
  = render 'form'